### ISSUE TITLE
Iphone image size issue not able to click next button

### ISSUE THREAD

**Issue by PriyansuMaurya** [dev-shetty/Portfolio#1]
The representation of the initial project, **Chromatico**, on the [projects](https://deveesh.vercel.app/projects) page doesn't appear favorable. Consequently, the subsequent next button also shifts downward, users to able to scroll unless he is on full screen.

![image](https://github.com/Deveesh-Shetty/Portfolio/assets/101447544/821acf50-1737-4873-bb7a-b7fc290c1924)

![image](https://github.com/Deveesh-Shetty/Portfolio/assets/101447544/c92dbc0f-ccc7-4c3e-a31b-c62cfd8e1613)

I would suggest making the size of iphone image smaller.

**Comment by dev-shetty** [comment]
Thanks for bringing that to notice! Will fix that...

**Comment by dev-shetty** [comment]
@PriyansuMaurya can u confirm whether the issue is fixed? If not will make changes in the PR

**Comment by dev-shetty** [comment]
Closing this issue as I will be redesigning the page completely!
